### ISSUE TITLE
IDE warnings when importing modules

### ISSUE THREAD

**Issue by AlexLemna** [AlexLemna/rosevomit#12]
I'm getting some warnings (but not outright errors) about unresolved imports, which I'm not entirely sure how to handle.

![UnresolvedImportError](https://user-images.githubusercontent.com/25907117/57103237-de588100-6cea-11e9-9d8d-3e89de3719de.PNG)

Possibly related to the fact that I've got blank `__init__.py` files?  The program seems to run fine, but the IDEs keep freaking out.

**Comment by AlexLemna** [comment]
Seems I'm not alone.

* Two issues raised on the VSCode-Python GitHub page: [#3840](https://github.com/Microsoft/vscode-python/issues/3840) and [#4784](https://github.com/Microsoft/vscode-python/issues/4784)
* A [question](https://stackoverflow.com/questions/53939751/pylint-unresolved-import-error-in-visual-studio-code) in StackOverflow

Possible open issue I can contribute to is here, [#5518](https://github.com/Microsoft/vscode-python/issues/5518).

**Comment by karrtikr** [comment]
Please use #5518 to provide more info.

**Comment by AlexLemna** [comment]
Cool! I'm pretty new to GitHub - I didn't realize tagging the issue numbers would notify you guys! I've provided more info on #5518.

**Comment by AlexLemna** [comment]
UPDATE: Issue was fixed thanks to @karrtikr's [advice](https://github.com/Microsoft/vscode-python/issues/5518#issuecomment-488950127) . See my comment [here](https://github.com/Microsoft/vscode-python/issues/5518#issuecomment-489206016).
